[package]
name = "lalu_asm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6"
# enum-map = "2.4"
once_cell = "1"
derive_more = "0"
